name: Compile Examples

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to external resources (libraries, platforms).
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:samd:mkrwifi1010
            platforms: |
              - name: arduino:samd
            libraries: |
              - name: Arduino_SpiNINA
            artifact-name-suffix: arduino-samd-mkrwifi1010
          - fqbn: arduino:samd:nano_33_iot
            platforms: |
              - name: arduino:samd
            libraries: |
              - name: Arduino_SpiNINA
            artifact-name-suffix: arduino-samd-nano_33_iot
          - fqbn: arduino:megaavr:uno2018:mode=on
            platforms: |
              - name: arduino:megaavr
            libraries: |
              - name: Arduino_SpiNINA
            artifact-name-suffix: arduino-megaavr-uno2018
          - fqbn: arduino:mbed_nano:nano33ble
            platforms: |
              - name: arduino:mbed_nano
            libraries: ""
            artifact-name-suffix: arduino-mbed_nano-nano33ble
          - fqbn: arduino:mbed_nano:nanorp2040connect
            platforms: |
              - name: arduino:mbed_nano
            libraries: |
              - name: Arduino_SpiNINA
            artifact-name-suffix: arduino-mbed_nano-nanorp2040connect
          - fqbn: arduino:mbed_portenta:envie_m7
            platforms: |
              - name: arduino:mbed_portenta
            libraries: ""
            artifact-name-suffix: arduino-mbed_portenta-envie_m7
          - fqbn: arduino:mbed_nicla:nicla_vision
            platforms: |
              - name: arduino:mbed_nicla
            libraries: ""
            artifact-name-suffix: arduino-mbed_nicla-nicla_vision
          - fqbn: arduino:mbed_giga:giga
            platforms: |
              - name: arduino:mbed_giga
            libraries: ""
            artifact-name-suffix: arduino-mbed_giga-giga
          - fqbn: arduino:mbed_opta:opta
            platforms: |
              - name: arduino:mbed_opta
            libraries: ""
            artifact-name-suffix: arduino-mbed_opta-opta
          - fqbn: arduino:renesas_uno:unor4wifi
            platforms: |
              - name: arduino:renesas_uno
            libraries: ""
            artifact-name-suffix: arduino-renesas_uno-unor4wifi
          - fqbn: arduino:renesas_portenta:portenta_c33
            platforms: |
              - name: arduino:renesas_portenta
            libraries: ""
            artifact-name-suffix: arduino-renesas_portenta-portenta_c33
          - fqbn: arduino:esp32:nano_nora
            platforms: |
              - name: arduino:esp32
            libraries: ""
            artifact-name-suffix: arduino-esp32-nano_nora
          - fqbn: arduino:zephyr_main:giga
            platforms: |
              - name: arduino:zephyr_main
            libraries: ""
            artifact-name-suffix: arduino-zephyr_main-giga
          - fqbn: arduino:zephyr_main:nano33ble
            platforms: |
              - name: arduino:zephyr_main
            libraries: ""
            artifact-name-suffix: arduino-zephyr_main-nano33ble
          - fqbn: arduino:zephyr_main:portentah7
            platforms: |
              - name: arduino:zephyr_main
            libraries: ""
            artifact-name-suffix: arduino-zephyr_main-portentah7
          - fqbn: arduino:zephyr_main:niclasense
            platforms: |
              - name: arduino:zephyr_main
            libraries: ""
            artifact-name-suffix: arduino-zephyr_main-niclasense
          - fqbn: arduino:zephyr_main:portentac33
            platforms: |
              - name: arduino:zephyr_main
            libraries: ""
            artifact-name-suffix: arduino-zephyr_main-portentac33
          - fqbn: arduino:zephyr_main:opta
            platforms: |
              - name: arduino:zephyr_main
            libraries: ""
            artifact-name-suffix: arduino-zephyr_main-opta
          - fqbn: arduino:zephyr:unoq
            platforms: |
              - name: arduino:zephyr
            libraries: |
              - name: MsgPack
            artifact-name-suffix: arduino-zephyr-unoq

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            # Install the library from the local path.
            - source-path: ./
            ${{ matrix.board.libraries }}
          sketch-paths: |
            - examples
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}

  build-for-esp32:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        fqbn:
          - esp32:esp32:esp32
          - esp32:esp32:esp32s3
          - esp32:esp32:esp32c3
          - esp32:esp32:esp32c6
          - esp32:esp32:esp32h2
          # Not supported out of the box by ESP32 Arduino core
          #- esp32:esp32:esp32c2

    steps:
      - uses: actions/checkout@v6
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          libraries: |
            ${{ matrix.libraries }}
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          sketch-paths: |
            - examples/Central/Scan
            - examples/Central/PeripheralExplorer
            - examples/Central/ScanCallback
            - examples/Central/SensorTagButton
            - examples/Peripheral/Advertising/EnhancedAdvertising
            - examples/Peripheral/Advertising/RawDataAdvertising
          cli-compile-flags: |
            - --warnings="none"
